spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tests2
    username: postgres
    password: jonatas123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 6161

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
    instances:
      produtoA:
        baseConfig: default
        waitDurationInOpenState: 5000


