spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tests
    username: postgres
    password: jonatas123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 6060